import dns from 'node:dns/promises'
dns.setServers(["1.1.1.1", "1.0.0.1"])

import mongoose from 'mongoose'
import dotenv from 'dotenv'
import connectDB from './config/db.js'
import Product from './models/productModel.js'
import User from './models/userModel.js'

dotenv.config()
connectDB()

const importData = async () => {
    try {
        await Product.deleteMany()

        const adminUser = await User.findOne({ isAdmin: true })

        const products = [
            // TELEFONI
            {
                user: adminUser._id,
                name: 'iPhone 14 Pro',
                image: 'https://images.unsplash.com/photo-1664478546384-d57ffe74a78c?w=400',
                description: 'Odličan iPhone u odličnom stanju, malo korišćen.',
                price: 850,
                category: 'Telefoni',
                countInStock: 3,
                rating: 4.5,
                numReviews: 12,
            },
            {
                user: adminUser._id,
                name: 'Samsung Galaxy S23',
                image: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400',
                description: 'Samsung Galaxy S23, kupljen pre 6 meseci.',
                price: 650,
                category: 'Telefoni',
                countInStock: 1,
                rating: 4.0,
                numReviews: 8,
            },
            {
                user: adminUser._id,
                name: 'Xiaomi Redmi Note 12',
                image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400',
                description: 'Xiaomi Redmi Note 12, 128GB, odlično stanje.',
                price: 250,
                category: 'Telefoni',
                countInStock: 2,
                rating: 4.2,
                numReviews: 6,
            },
            {
                user: adminUser._id,
                name: 'iPhone 13',
                image: 'https://images.unsplash.com/photo-1632633173522-47456de71b76?w=400',
                description: 'iPhone 13, 128GB, crna boja, odlično stanje.',
                price: 700,
                category: 'Telefoni',
                countInStock: 2,
                rating: 4.6,
                numReviews: 18,
            },
            {
                user: adminUser._id,
                name: 'Huawei P50 Pro',
                image: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=400',
                description: 'Huawei P50 Pro, odličan fotoaparat, malo korišćen.',
                price: 550,
                category: 'Telefoni',
                countInStock: 1,
                rating: 4.3,
                numReviews: 9,
            },
            {
                user: adminUser._id,
                name: 'Xiaomi Pixel 7',
                image: 'https://images.unsplash.com/photo-1598327105854-c8674faddf79?w=400',
                description: 'Xaomi Pixel 7, 256GB, čist Android, odlična kamera.',
                price: 600,
                category: 'Telefoni',
                countInStock: 1,
                rating: 4.4,
                numReviews: 11,
            },
            // LAPTOPOVI
            {
                user: adminUser._id,
                name: 'Laptop Lenovo ThinkPad',
                image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400',
                description: 'Poslovni laptop, idealan za rad i učenje.',
                price: 500,
                category: 'Laptopovi',
                countInStock: 2,
                rating: 4.8,
                numReviews: 20,
            },
            {
                user: adminUser._id,
                name: 'MacBook Pro 14',
                image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400',
                description: 'Apple MacBook Pro 14, M2 čip, 16GB RAM.',
                price: 1800,
                category: 'Laptopovi',
                countInStock: 1,
                rating: 5.0,
                numReviews: 15,
            },
            {
                user: adminUser._id,
                name: 'HP Pavilion 15',
                image: 'https://kaas.hpcloud.hp.com/PROD/v2/renderbinary/6338340/6344509/con-win-nb-p-felicette-22c1-hp-pavilion-laptop-15-eh2000-specification/con-nb-felicitte-hp-pavilion-laptop-15-eh2000-product-image',
                description: 'HP Pavilion 15, Intel i5, 8GB RAM, 512GB SSD.',
                price: 600,
                category: 'Laptopovi',
                countInStock: 1,
                rating: 4.3,
                numReviews: 10,
            },
            {
                user: adminUser._id,
                name: 'Dell XPS 15',
                image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400',
                description: 'Dell XPS 15, Intel i7, 16GB RAM, odličan za dizajn.',
                price: 1200,
                category: 'Laptopovi',
                countInStock: 1,
                rating: 4.7,
                numReviews: 14,
            },
            {
                user: adminUser._id,
                name: 'Asus ROG Gaming Laptop',
                image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=400',
                description: 'Asus ROG gaming laptop, RTX 3060, 144Hz ekran.',
                price: 1400,
                category: 'Laptopovi',
                countInStock: 1,
                rating: 4.9,
                numReviews: 22,
            },
            {
                user: adminUser._id,
                name: 'Acer Aspire 5',
                image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=400',
                description: 'Acer Aspire 5, AMD Ryzen 5, idealan za studente.',
                price: 450,
                category: 'Laptopovi',
                countInStock: 2,
                rating: 4.1,
                numReviews: 16,
            },
            // GAMING
            {
                user: adminUser._id,
                name: 'PlayStation 5',
                image: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400',
                description: 'PS5 konzola sa dva džojstika, sve u kutiji.',
                price: 450,
                category: 'Gaming',
                countInStock: 1,
                rating: 5.0,
                numReviews: 30,
            },
            {
                user: adminUser._id,
                name: 'PlayStation 4',
                image: 'https://images.unsplash.com/photo-1486401899868-0e435ed85128?w=400',
                description: 'PS4 konzola sa 10 igrica, odlično stanje.',
                price: 200,
                category: 'Gaming',
                countInStock: 2,
                rating: 4.3,
                numReviews: 18,
            },
            {
                user: adminUser._id,
                name: 'Xbox Series X',
                image: 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=400',
                description: 'Xbox Series X, malo korišćen, dolazi sa 5 igrica.',
                price: 400,
                category: 'Gaming',
                countInStock: 1,
                rating: 4.7,
                numReviews: 25,
            },
            {
                user: adminUser._id,
                name: 'Nintendo Switch',
                image: 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=400',
                description: 'Nintendo Switch OLED, dolazi sa 5 igrica.',
                price: 280,
                category: 'Gaming',
                countInStock: 2,
                rating: 4.8,
                numReviews: 27,
            },
            {
                user: adminUser._id,
                name: 'Gaming Miš Logitech G502',
                image: 'https://images.unsplash.com/photo-1527814050087-3793815479db?w=400',
                description: 'Logitech G502 gaming miš, kao nov.',
                price: 50,
                category: 'Gaming',
                countInStock: 3,
                rating: 4.6,
                numReviews: 20,
            },
            {
                user: adminUser._id,
                name: 'Gaming Tastatura Razer',
                image: 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=400',
                description: 'Razer mehanička tastatura, RGB osvetljenje.',
                price: 80,
                category: 'Gaming',
                countInStock: 2,
                rating: 4.5,
                numReviews: 15,
            },
            // OBUĆA
            {
                user: adminUser._id,
                name: 'Nike Air Max 90',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSv27x7o-l5QeV6Pncj9Ej9h5o-Q0KpjbxGQ&s',
                description: 'Patike broj 43, nošene samo jednom.',
                price: 80,
                category: 'Obuća',
                countInStock: 1,
                rating: 3.5,
                numReviews: 5,
            },
            {
                user: adminUser._id,
                name: 'Adidas Ultraboost',
                image: 'https://www.etsport.rs/files/thumbs/files/images/products/media/ID1/ID1747/images/thumbs_800/ID1747_800_800px.jpg',
                description: 'Adidas Ultraboost patike, broj 42, kao nove.',
                price: 120,
                category: 'Obuća',
                countInStock: 1,
                rating: 4.6,
                numReviews: 9,
            },
            {
                user: adminUser._id,
                name: 'Puma RS-X',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5gw9Tkmw2r-y9xWHcAqlJeEQjs0ln_vRWGA&s',
                description: 'Puma RS-X patike broj 44, nošene par puta.',
                price: 70,
                category: 'Obuća',
                countInStock: 2,
                rating: 4.1,
                numReviews: 7,
            },
            {
                user: adminUser._id,
                name: 'Converse Chuck Taylor',
                image: 'https://dr9l7gb9cebpv.cloudfront.net/media/catalog/product/cache/2774d42b8e55ba58cfe3fc9632392955/m/9/m9160_a_107x1.jpg',
                description: 'Converse Chuck Taylor, broj 41, crne boje.',
                price: 55,
                category: 'Obuća',
                countInStock: 2,
                rating: 4.3,
                numReviews: 12,
            },
            {
                user: adminUser._id,
                name: 'Vans Old Skool',
                image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400',
                description: 'Vans Old Skool, broj 42, klasičan crno-beli dizajn.',
                price: 65,
                category: 'Obuća',
                countInStock: 1,
                rating: 4.4,
                numReviews: 10,
            },
            {
                user: adminUser._id,
                name: 'New Balance 574',
                image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=400',
                description: 'New Balance 574, broj 43, siva boja, kao nove.',
                price: 90,
                category: 'Obuća',
                countInStock: 1,
                rating: 4.5,
                numReviews: 8,
            },
            // TABLETI
            {
                user: adminUser._id,
                name: 'iPad Air 5',
                image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400',
                description: 'Apple iPad Air 5, 64GB, WiFi, malo korišćen.',
                price: 600,
                category: 'Tableti',
                countInStock: 2,
                rating: 4.7,
                numReviews: 11,
            },
            {
                user: adminUser._id,
                name: 'Samsung Galaxy Tab S8',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmxGnfy8xF4IQgnmAI1kjFU3jaOTgFhA3XQA&s',
                description: 'Samsung tablet, 128GB, odličan za crtanje i rad.',
                price: 500,
                category: 'Tableti',
                countInStock: 1,
                rating: 4.5,
                numReviews: 13,
            },
            {
                user: adminUser._id,
                name: 'iPad Pro 12.9',
                image: 'https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?w=400',
                description: 'iPad Pro 12.9, M1 čip, 256GB, sa Apple Pencilom.',
                price: 1100,
                category: 'Tableti',
                countInStock: 1,
                rating: 5.0,
                numReviews: 19,
            },
            {
                user: adminUser._id,
                name: 'Huawei MatePad Pro',
                image: 'https://www.tehnomedia.rs/products/69185_huge2_0_cached.jpg',
                description: 'Huawei MatePad Pro, 128GB, odličan ekran.',
                price: 450,
                category: 'Tableti',
                countInStock: 1,
                rating: 4.4,
                numReviews: 8,
            },
            {
                user: adminUser._id,
                name: 'Lenovo Tab P12 Pro',
                image: 'https://download.lenovo.com/km/media/images/HT513080/top_20211118030548380.png',
                description: 'Lenovo Tab P12 Pro, AMOLED ekran, 256GB.',
                price: 550,
                category: 'Tableti',
                countInStock: 1,
                rating: 4.6,
                numReviews: 10,
            },
            {
                user: adminUser._id,
                name: 'Amazon Fire HD 10',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSZvkg5q0AU4FO48z8tebOFSB6Brf7TAWSsQ&s',
                description: 'Amazon Fire HD 10, idealan za čitanje i filmove.',
                price: 120,
                category: 'Tableti',
                countInStock: 3,
                rating: 4.0,
                numReviews: 14,
            },
            // SPORT
            {
                user: adminUser._id,
                name: 'Bicikl Trek',
                image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=400',
                description: 'Planinski bicikl, servisiran ove godine.',
                price: 300,
                category: 'Sport',
                countInStock: 1,
                rating: 4.2,
                numReviews: 7,
            },
            {
                user: adminUser._id,
                name: 'Fitnes Bicikl',
                image: 'https://img.ep-cdn.com/i/500/500/ge/geytdlqomjahfwcizrvk/shoppster-fitness-sobni-bicikl-magnetni-sb53-cene.jpg',
                description: 'Sobni fitnes bicikl, malo korišćen, odlično stanje.',
                price: 180,
                category: 'Sport',
                countInStock: 1,
                rating: 4.0,
                numReviews: 5,
            },
            {
                user: adminUser._id,
                name: 'Skije Rossignol',
                image: 'https://www.m-bikeshop.com/upload/catalog/product/37807/RANPM02D0153S_1_Skije-ROSSIGNOL-Hero-Elite-MT-TI-CAM-KONEC-DFT-+-Vezovi-FCNCS04_694ff2255b171.jpg',
                description: 'Skije 160cm sa vezovima, korišćene jednu sezonu.',
                price: 220,
                category: 'Sport',
                countInStock: 1,
                rating: 4.4,
                numReviews: 8,
            },
            {
                user: adminUser._id,
                name: 'Tenis Reket Wilson',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbq9i1HN-39GruLkRqLfEx1mi4q5fwynVl1Q&s',
                description: 'Wilson tenis reket, profesionalni, malo korišćen.',
                price: 90,
                category: 'Sport',
                countInStock: 2,
                rating: 4.5,
                numReviews: 11,
            },
            {
                user: adminUser._id,
                name: 'Fudbalska Lopta Adidas',
                image: 'https://images.unsplash.com/photo-1614632537197-38a17061c2bd?w=400',
                description: 'Adidas fudbalska lopta, veličina 5, kao nova.',
                price: 40,
                category: 'Sport',
                countInStock: 3,
                rating: 4.3,
                numReviews: 9,
            },
            {
                user: adminUser._id,
                name: 'Bučice 10kg Set',
                image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400',
                description: 'Set bučica 10kg, gumene, odlično za kućni trening.',
                price: 60,
                category: 'Sport',
                countInStock: 2,
                rating: 4.6,
                numReviews: 13,
            },
            // KAMERE
            {
                user: adminUser._id,
                name: 'Canon EOS 250D',
                image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400',
                description: 'Canon DSLR fotoaparat sa objektivom 18-55mm.',
                price: 550,
                category: 'Kamere',
                countInStock: 1,
                rating: 4.9,
                numReviews: 14,
            },
            {
                user: adminUser._id,
                name: 'Sony Alpha A6000',
                image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400',
                description: 'Sony mirrorless kamera, odlična za fotografiju.',
                price: 450,
                category: 'Kamere',
                countInStock: 1,
                rating: 4.8,
                numReviews: 16,
            },
            {
                user: adminUser._id,
                name: 'Nikon D3500',
                image: 'https://pcfoto.biz/Image/34476/Nikon-D3500-18-55-VR-70-300-VR.jpg',
                description: 'Nikon D3500, idealan za početnike, sa objektivom.',
                price: 400,
                category: 'Kamere',
                countInStock: 1,
                rating: 4.7,
                numReviews: 18,
            },
            {
                user: adminUser._id,
                name: 'GoPro Hero 11',
                image: 'https://static.gopro.com/assets/blta2b8522e5372af40/bltb0e158820591a2a1/645147b2d5d03c0794f168cd/pdp-h11b-SA-image02-1920-2x.png',
                description: 'GoPro Hero 11, vodootporna akciona kamera.',
                price: 300,
                category: 'Kamere',
                countInStock: 2,
                rating: 4.8,
                numReviews: 25,
            },
            {
                user: adminUser._id,
                name: 'DJI Mini 3 Dron',
                image: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=400',
                description: 'DJI Mini 3 dron sa kamerom, malo korišćen.',
                price: 600,
                category: 'Kamere',
                countInStock: 1,
                rating: 4.9,
                numReviews: 20,
            },
            {
                user: adminUser._id,
                name: 'Fujifilm Instax Mini',
                image: 'https://gigatron.vtexassets.com/arquivos/ids/270551/image64abe4424902e.jpg.jpg?v=639139695283900000',
                description: 'Fujifilm Instax Mini trenutni fotoaparat, roze boja.',
                price: 80,
                category: 'Kamere',
                countInStock: 3,
                rating: 4.5,
                numReviews: 22,
            },
            // KUĆNI APARATI
            {
                user: adminUser._id,
                name: 'Xiaomi Robot Usisivač',
                image: 'https://mi-srbija.rs/storage/product/thumbs/96/21/xiaomi-robot-usisivac-mop-10-x10-6194-1997x1997.jpg',
                description: 'Xiaomi robot usisivač, automatsko čišćenje.',
                price: 250,
                category: 'Kućni aparati',
                countInStock: 1,
                rating: 4.4,
                numReviews: 22,
            },
            {
                user: adminUser._id,
                name: 'Philips Air Fryer',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRP4oTEK-HgOyPLKQHyWz2r5gzsZ4eYtFPF2w&s',
                description: 'Philips air fryer 4.1L, kao nov, malo korišćen.',
                price: 100,
                category: 'Kućni aparati',
                countInStock: 2,
                rating: 4.6,
                numReviews: 19,
            },
            {
                user: adminUser._id,
                name: 'Nescafe Aparat za Kafu',
                image: 'https://img.ep-cdn.com/i/500/500/fw/fwdvabpzuliyrngtskxj/nespresso-aparat-za-kafu-vertuo-pop-crni-gdv2-eubkne-s-cene.jpg',
                description: 'Nescafe Dolce Gusto aparat, dolazi sa 3 kutije kapsula.',
                price: 60,
                category: 'Kućni aparati',
                countInStock: 3,
                rating: 4.3,
                numReviews: 17,
            },
            {
                user: adminUser._id,
                name: 'Bosch Mikser',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUzMGadeGewOk1hewfIE-NF9K0HYoZHy4V4A&s',
                description: 'Bosch kuhinjski mikser, 1000W, malo korišćen.',
                price: 80,
                category: 'Kućni aparati',
                countInStock: 1,
                rating: 4.5,
                numReviews: 12,
            },
            {
                user: adminUser._id,
                name: 'Philips Pegla na Paru',
                image: 'https://img.ep-cdn.com/i/500/500/ew/ewcgaiuxdvnzpbmortyh/philips-parna-stanica-psg6064-80-cene.jpg',
                description: 'Philips pegla na paru, 2400W, kao nova.',
                price: 45,
                category: 'Kućni aparati',
                countInStock: 2,
                rating: 4.2,
                numReviews: 8,
            },
            {
                user: adminUser._id,
                name: 'Dyson Usisivač V11',
                image: 'https://ecotech-shop.rs/wp-content/uploads/2024/12/Dyson-V11-Advanced-479333-bezicni-usisivac-slika1.jpg',
                description: 'Dyson V11 bežični usisivač, top performanse.',
                price: 350,
                category: 'Kućni aparati',
                countInStock: 1,
                rating: 4.9,
                numReviews: 28,
            },
            // AUDIO
            {
                user: adminUser._id,
                name: 'Sony WH-1000XM4',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTioWihqcsSOOeHzjf6AxMkbFqGdqGJrJCbZQ&s',
                description: 'Sony bežične slušalice sa noise canceling, top kvalitet.',
                price: 220,
                category: 'Audio',
                countInStock: 2,
                rating: 5.0,
                numReviews: 35,
            },
            {
                user: adminUser._id,
                name: 'JBL Flip 6',
                image: 'https://m.media-amazon.com/images/I/61Eaj593GtL._AC_UF1000,1000_QL80_.jpg',
                description: 'JBL Bluetooth zvučnik, vodootporan, odlican zvuk.',
                price: 90,
                category: 'Audio',
                countInStock: 2,
                rating: 4.7,
                numReviews: 28,
            },
            {
                user: adminUser._id,
                name: 'Bose QuietComfort 45',
                image: 'https://www.digiexpert.si/_media/cvoEshop/media/61a8d1ea27fbd9001c5d0014_bose-quietcomfort-45-black-2_smallLF.png',
                description: 'Bose QC45 slušalice, premium noise canceling.',
                price: 280,
                category: 'Audio',
                countInStock: 1,
                rating: 4.9,
                numReviews: 30,
            },
            {
                user: adminUser._id,
                name: 'Apple AirPods Pro',
                image: 'https://www.mytrendyphone.rs/images/AirPods-Pro-2nd-generation-with-MagSafe-Charging-Case-USB-C-MTJV3ZM-A-White-0195949052637-08072024-00-p.webp',
                description: 'Apple AirPods Pro 2, aktivno poništavanje buke.',
                price: 200,
                category: 'Audio',
                countInStock: 2,
                rating: 4.8,
                numReviews: 40,
            },
            {
                user: adminUser._id,
                name: 'Marshall Acton III',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbYMoVC3aThAzu6PmjxSpM9iTolU0G5VMz_Q&s',
                description: 'Marshall Acton III kućni zvučnik, retro dizajn.',
                price: 320,
                category: 'Audio',
                countInStock: 1,
                rating: 4.9,
                numReviews: 18,
            },
            {
                user: adminUser._id,
                name: 'Sennheiser HD 650',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsEvcdnvA7wuxDoDHNhSuvCscNZ01oYHB6pw&s',
                description: 'Sennheiser HD 650 studijske slušalice, vrhunski zvuk.',
                price: 250,
                category: 'Audio',
                countInStock: 1,
                rating: 5.0,
                numReviews: 22,
            },
            // SATOVI
            {
                user: adminUser._id,
                name: 'Apple Watch Series 8',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbdLJf_YFqfUL9YOCXrIl_PbqV3OBAVyXIEw&s',
                description: 'Apple Watch Series 8, 45mm, GPS, malo korišćen.',
                price: 380,
                category: 'Satovi',
                countInStock: 1,
                rating: 4.8,
                numReviews: 21,
            },
            {
                user: adminUser._id,
                name: 'Samsung Galaxy Watch 5',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtUWUHQeyZp2aMnLl6MlkuLEJAStU3XARWrQ&s',
                description: 'Samsung Galaxy Watch 5, 44mm, crna boja.',
                price: 250,
                category: 'Satovi',
                countInStock: 2,
                rating: 4.6,
                numReviews: 15,
            },
            {
                user: adminUser._id,
                name: 'Garmin Forerunner 255',
                image: 'https://www.tehnomedia.rs/products/117726_webp_2_cached.jpg',
                description: 'Garmin sportski sat, GPS, praćenje zdravlja.',
                price: 300,
                category: 'Satovi',
                countInStock: 1,
                rating: 4.7,
                numReviews: 17,
            },
            {
                user: adminUser._id,
                name: 'Casio G-Shock',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQo06dr3kvF2C95V1Xhk5Tl3PwkgeMzoeGRg&s',
                description: 'Casio G-Shock, otporan na udarce i vodu.',
                price: 120,
                category: 'Satovi',
                countInStock: 2,
                rating: 4.5,
                numReviews: 20,
            },
            {
                user: adminUser._id,
                name: 'Fossil Gen 6',
                image: 'https://images.kupujemprodajem.com/photos/oglasi/8/76/120205768/120205768_624a242d434ef0-59306462FTW6078_main-no.jpg',
                description: 'Fossil Gen 6 smartwatch, Wear OS, elegantan dizajn.',
                price: 200,
                category: 'Satovi',
                countInStock: 1,
                rating: 4.4,
                numReviews: 12,
            },
            {
                user: adminUser._id,
                name: 'Fitbit Versa 4',
                image: 'https://gigatron.vtexassets.com/arquivos/ids/400786-750-750/image64afa5a76a733.jpg.jpg?v=639140179285570000',
                description: 'Fitbit Versa 4, praćenje aktivnosti i sna.',
                price: 160,
                category: 'Satovi',
                countInStock: 2,
                rating: 4.3,
                numReviews: 14,
            },
        ]

        await Product.insertMany(products)
        console.log('Podaci uspešno uvezeni!')
        process.exit()
    } catch (error) {
        console.log(`Greška: ${error.message}`)
        process.exit(1)
    }
}

importData()