import dns from 'node:dns/promises'
dns.setServers(["1.1.1.1", "1.0.0.1"])

import mongoose from 'mongoose'
import dotenv from 'dotenv'
import connectDB from './config/db.js'
import Product from './models/productModel.js'
import User from './models/userModel.js'

dotenv.config()
connectDB()

const importData = async () => {
    try {
        await Product.deleteMany()

        const adminUser = await User.findOne({ isAdmin: true })

        const products = [
            {
                user: adminUser._id,
                name: 'iPhone 14 Pro',
                image: 'https://via.placeholder.com/300x200',
                description: 'Odličan iPhone u odličnom stanju, malo korišćen.',
                price: 850,
                category: 'Telefoni',
                countInStock: 3,
                rating: 4.5,
                numReviews: 12,
            },
            {
                user: adminUser._id,
                name: 'Samsung Galaxy S23',
                image: 'https://via.placeholder.com/300x200',
                description: 'Samsung Galaxy S23, kupljen pre 6 meseci.',
                price: 650,
                category: 'Telefoni',
                countInStock: 1,
                rating: 4.0,
                numReviews: 8,
            },
            {
                user: adminUser._id,
                name: 'Xiaomi Redmi Note 12',
                image: 'https://via.placeholder.com/300x200',
                description: 'Xiaomi Redmi Note 12, 128GB, odlično stanje.',
                price: 250,
                category: 'Telefoni',
                countInStock: 2,
                rating: 4.2,
                numReviews: 6,
            },
            {
                user: adminUser._id,
                name: 'Laptop Lenovo ThinkPad',
                image: 'https://via.placeholder.com/300x200',
                description: 'Poslovni laptop, idealan za rad i učenje.',
                price: 500,
                category: 'Laptopovi',
                countInStock: 2,
                rating: 4.8,
                numReviews: 20,
            },
            {
                user: adminUser._id,
                name: 'MacBook Pro 14',
                image: 'https://via.placeholder.com/300x200',
                description: 'Apple MacBook Pro 14, M2 čip, 16GB RAM.',
                price: 1800,
                category: 'Laptopovi',
                countInStock: 1,
                rating: 5.0,
                numReviews: 15,
            },
            {
                user: adminUser._id,
                name: 'HP Pavilion 15',
                image: 'https://via.placeholder.com/300x200',
                description: 'HP Pavilion 15, Intel i5, 8GB RAM, 512GB SSD.',
                price: 600,
                category: 'Laptopovi',
                countInStock: 1,
                rating: 4.3,
                numReviews: 10,
            },
            {
                user: adminUser._id,
                name: 'PlayStation 5',
                image: 'https://via.placeholder.com/300x200',
                description: 'PS5 konzola sa dva džojstika, sve u kutiji.',
                price: 450,
                category: 'Gaming',
                countInStock: 1,
                rating: 5.0,
                numReviews: 30,
            },
            {
                user: adminUser._id,
                name: 'PlayStation 4',
                image: 'https://via.placeholder.com/300x200',
                description: 'PS4 konzola sa 10 igrica, odlično stanje.',
                price: 200,
                category: 'Gaming',
                countInStock: 2,
                rating: 4.3,
                numReviews: 18,
            },
            {
                user: adminUser._id,
                name: 'Xbox Series X',
                image: 'https://via.placeholder.com/300x200',
                description: 'Xbox Series X, malo korišćen, dolazi sa 5 igrica.',
                price: 400,
                category: 'Gaming',
                countInStock: 1,
                rating: 4.7,
                numReviews: 25,
            },
            {
                user: adminUser._id,
                name: 'Nike Air Max 90',
                image: 'https://via.placeholder.com/300x200',
                description: 'Patike broj 43, nošene samo jednom.',
                price: 80,
                category: 'Obuća',
                countInStock: 1,
                rating: 3.5,
                numReviews: 5,
            },
            {
                user: adminUser._id,
                name: 'Adidas Ultraboost',
                image: 'https://via.placeholder.com/300x200',
                description: 'Adidas Ultraboost patike, broj 42, kao nove.',
                price: 120,
                category: 'Obuća',
                countInStock: 1,
                rating: 4.6,
                numReviews: 9,
            },
            {
                user: adminUser._id,
                name: 'Puma RS-X',
                image: 'https://via.placeholder.com/300x200',
                description: 'Puma RS-X patike broj 44, nošene par puta.',
                price: 70,
                category: 'Obuća',
                countInStock: 2,
                rating: 4.1,
                numReviews: 7,
            },
            {
                user: adminUser._id,
                name: 'iPad Air 5',
                image: 'https://via.placeholder.com/300x200',
                description: 'Apple iPad Air 5, 64GB, WiFi, malo korišćen.',
                price: 600,
                category: 'Tableti',
                countInStock: 2,
                rating: 4.7,
                numReviews: 11,
            },
            {
                user: adminUser._id,
                name: 'Samsung Galaxy Tab S8',
                image: 'https://via.placeholder.com/300x200',
                description: 'Samsung tablet, 128GB, odličan za crtanje i rad.',
                price: 500,
                category: 'Tableti',
                countInStock: 1,
                rating: 4.5,
                numReviews: 13,
            },
            {
                user: adminUser._id,
                name: 'Bicikl Trek',
                image: 'https://via.placeholder.com/300x200',
                description: 'Planinski bicikl, servisiran ove godine.',
                price: 300,
                category: 'Sport',
                countInStock: 1,
                rating: 4.2,
                numReviews: 7,
            },
            {
                user: adminUser._id,
                name: 'Fitnes Bicikl',
                image: 'https://via.placeholder.com/300x200',
                description: 'Sobni fitnes bicikl, malo korišćen, odlično stanje.',
                price: 180,
                category: 'Sport',
                countInStock: 1,
                rating: 4.0,
                numReviews: 5,
            },
            {
                user: adminUser._id,
                name: 'Skije Rossignol',
                image: 'https://via.placeholder.com/300x200',
                description: 'Skije 160cm sa vezovima, korišćene jednu sezonu.',
                price: 220,
                category: 'Sport',
                countInStock: 1,
                rating: 4.4,
                numReviews: 8,
            },
            {
                user: adminUser._id,
                name: 'Canon EOS 250D',
                image: 'https://via.placeholder.com/300x200',
                description: 'Canon DSLR fotoaparat sa objektivom 18-55mm.',
                price: 550,
                category: 'Fotografija',
                countInStock: 1,
                rating: 4.9,
                numReviews: 14,
            },
            {
                user: adminUser._id,
                name: 'Sony Alpha A6000',
                image: 'https://via.placeholder.com/300x200',
                description: 'Sony mirrorless kamera, odlična za fotografiju.',
                price: 450,
                category: 'Fotografija',
                countInStock: 1,
                rating: 4.8,
                numReviews: 16,
            },
            {
                user: adminUser._id,
                name: 'Xiaomi Robot Usisivač',
                image: 'https://via.placeholder.com/300x200',
                description: 'Xiaomi robot usisivač, automatsko čišćenje.',
                price: 250,
                category: 'Kućni aparati',
                countInStock: 1,
                rating: 4.4,
                numReviews: 22,
            },
            {
                user: adminUser._id,
                name: 'Philips Air Fryer',
                image: 'https://via.placeholder.com/300x200',
                description: 'Philips air fryer 4.1L, kao nov, malo korišćen.',
                price: 100,
                category: 'Kućni aparati',
                countInStock: 2,
                rating: 4.6,
                numReviews: 19,
            },
            {
                user: adminUser._id,
                name: 'Nescafe Aparat za Kafu',
                image: 'https://via.placeholder.com/300x200',
                description: 'Nescafe Dolce Gusto aparat, dolazi sa 3 kutije kapsula.',
                price: 60,
                category: 'Kućni aparati',
                countInStock: 3,
                rating: 4.3,
                numReviews: 17,
            },
            {
                user: adminUser._id,
                name: 'Sony WH-1000XM4',
                image: 'https://via.placeholder.com/300x200',
                description: 'Sony bežične slušalice sa noise canceling, top kvalitet.',
                price: 220,
                category: 'Audio',
                countInStock: 2,
                rating: 5.0,
                numReviews: 35,
            },
            {
                user: adminUser._id,
                name: 'JBL Flip 6',
                image: 'https://via.placeholder.com/300x200',
                description: 'JBL Bluetooth zvučnik, vodootporan, odlican zvuk.',
                price: 90,
                category: 'Audio',
                countInStock: 2,
                rating: 4.7,
                numReviews: 28,
            },
            {
                user: adminUser._id,
                name: 'Apple Watch Series 8',
                image: 'https://via.placeholder.com/300x200',
                description: 'Apple Watch Series 8, 45mm, GPS, malo korišćen.',
                price: 380,
                category: 'Satovi',
                countInStock: 1,
                rating: 4.8,
                numReviews: 21,
            },
        ]

        await Product.insertMany(products)
        console.log('Podaci uspešno uvezeni!')
        process.exit()
    } catch (error) {
        console.log(`Greška: ${error.message}`)
        process.exit(1)
    }
}

importData()